import Head from 'next/head'
import Navbar from '../components/Navbar';
import Leftside from '../components/Leftside';
import Rightside from '../components/Rightside';
import styles from '../styles/sections.module.scss';



export default function Home() {
  return (
    <>
      <Head>
        <title>Mohammed Harris | Software Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar/>
        <div className={styles.banner}>
          <div className={styles.leftside}>
            <Leftside />
          </div>
          <div className={styles.rightside}>
            <Rightside />
          </div>
        </div>
      </main>
    </>
  );
}
